# Generated by Django 5.2.2 on 2025-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.CharField(max_length=100)),
                ('remind_via', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms')], max_length=10)),
            ],
        ),
    ]
